name: 'Codious.Maximus (Azure Hosted Agent)'

trigger:
- develop

pool:
  name: 'maximus-development'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: maximus-development'
  inputs:
    ArtifactName: maximus-development