paths:
  /ping.info:
    get:
      description: Ping the server
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  response:
                    type: string
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Ping