paths:
  /comments.create:
    post:
      description: Create a comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        201:
          description: Comment is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments

  /comments.delete:
    post:
      descriptions: Delete a comment
      requestBody:
        content:
          application/json:
            schema:
              properties:
                _id:
                  type: string
                  format: bson
      responses:
        204:
          description: Comment is deleted
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        404:
          $ref: '#/components/responses/FourZeroFour'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments

  /comments.info:
    get:
      description: Get a comment
      parameters:
        - in: query
          name: id
          description: The ID of the comment
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        404:
          $ref: '#/components/responses/FourZeroFour'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments

  /comments.list:
    get:
      description: Get a list of comments
      parameters:
        - in: query
          name: sort
          description: The sort order
          schema:
            type: string
        - in: query
          name: limit
          description: The number of items
          schema:
            type: string
        - in: query
          name: skip
          description: The number of items to skip
          schema:
            type: string
        - in: query
          name: search
          description: The search term
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments

  /comments.update:
    post:
      description: Update a comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: Comment is updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        404:
          $ref: '#/components/responses/FourZeroFour'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments


  /comments.statuses:
    get:
      description: Get comment statuses
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  enum:
                    - approved
                    - denied
                    - pending
                    - spam
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Comments