paths:
  /vehicles.brands:
    get:
      description: Get a list of brands
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Vehicles

  /vehicles.create:
    post:
      description: Create an vehicle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        201:
          description: Vehicle is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Vehicles

  /vehicle.delete:
    post:
      descriptions: Delete an vehicle
      requestBody:
        content:
          application/json:
            schema:
              properties:
                _id:
                  type: string
                  format: bson
      responses:
        204:
          description: Vehicle is deleted
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        404:
          $ref: '#/components/responses/FourZeroFour'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Vehicles

  /vehicles.info:
    get:
      description: Get an vehicle
      parameters:
        - in: query
          name: id
          description: The ID of the vehicle
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        404:
          $ref: '#/components/responses/FourZeroFour'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Vehicles

  /vehicles.list:
    get:
      description: Get a list of vehicles
      parameters:
        - in: query
          name: sort
          description: The sort order
          schema:
            type: string
        - in: query
          name: limit
          description: The number of items
          schema:
            type: string
        - in: query
          name: skip
          description: The number of items to skip
          schema:
            type: string
        - in: query
          name: search
          description: The search term
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        401:
          $ref: '#/components/responses/FourZeroOne'
        403:
          $ref: '#/components/responses/FourZeroThree'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      security:
        - bearer: []
      tags:
        - Vehicles

  /vehicles.update:
      post:
        description: Update an vehicle
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        responses:
          200:
            description: Vehicle is updated
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Vehicle'
          400:
            $ref: '#/components/responses/FourZeroZero'
          401:
            $ref: '#/components/responses/FourZeroOne'
          403:
            $ref: '#/components/responses/FourZeroThree'
          404:
            $ref: '#/components/responses/FourZeroFour'
          5XX:
            $ref: '#/components/responses/FiveHundred'
        security:
          - bearer: []
        tags:
          - Vehicles