components:
  schemas:
    Jwt:
      properties:
        access_token:
          type: string
        expires_in:
          type: number
        refresh_token:
          type: string
        token_type:
          type: string

paths:
  /auth.forgot:
    post:
      description: Send a new password to the user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        204:
          description: Forgot password email has been send
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Authentication

  /auth.invite:
    post:
      description: Invite a user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        200:
          description: a Us
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Authentication

  /auth.login:
    post:
      description: Login with your credentials and receive a JWT token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jwt'
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Authentication

  /auth.refresh:
    post:
      description: refresh with your JWT refresh token and receive a new JWT access token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                token:
                  type: string
              required:
                - id
                - token
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jwt'
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Authentication

  /auth.reset:
    post:
      description: reset your password with your JWT token and new password
      requestBody:
        content:
          application/json:
            schema:
              properties:
                token:
                  type: string
                password:
                  type: string
              required:
                - token
                - password
      responses:
        204:
          description: Password has been reset and email has been send
        400:
          $ref: '#/components/responses/FourZeroZero'
        401:
          $ref: '#/components/responses/FourZeroOne'
        5XX:
          $ref: '#/components/responses/FiveHundred'
      tags:
        - Authentication